_id: H8YsYWKbw5kYlFLC
name: Bribes
permission:
  default: 0
folder: ''
flags: {}
content: |-
  <ul>
  <li>A peasant dowry&nbsp; 20-Charisma coins</li>
  <li>“Protection” for a small business&nbsp; 100-Charisma coins</li>
  <li>A government bribe&nbsp; 50-Charisma coins</li>
  <li>A compelling bribe&nbsp; 80-Charisma coins</li>
  <li>An offer you can’t refuse&nbsp; 500-Charisma coins</li>
  </ul>
